### PR TITLE
Gnome shell: update and clean scss code

### PR DESCRIPTION
**Pull request by drakkar1969**
This is a pretty comprehensive review of the gnome shell code, that basically does three things:
- Fixes a few typos in the scss code
- Removes redundant selectors/styling (i.e. styling that is no longer required in newer gnome shell versions), and replaces with newer selectors/styling (modifying to match Arc styling where necessary)
- Integrates styling from the default gnome shell theme into the Arc shell theme. Because the user shell theme (Arc in this case) is "overlaid" over the default shell theme, this is styling that was being "pulled in" anyway.

**NOTE**: these changes have only been applied to gnome shell versions 3.30 and 3.32, and a separate copy of the shell theme has been created for gnome shell version 3.32.

These changes should not change the visual appearance of the Arc shell theme (with a few exceptions, see below) - the difference is that the Arc shell theme is now "complete" or "self-contained", no longer relying on styling from the default shell theme.
In addition to the code being cleaner and updated to match newer shell versions, one of the main benefits of this change is that the Arc shell theme can be used in a `.gresource` file to style the login/unlock/lock screens without errors or visual glitches (see #98 for discussion). (I can post updated XML files in the discussion thread if and when this PR is merged).

**Elements with updated styling:**
- Onscreen keyboard (OSK): updated special key svg images, added shift key on/locked button states, added styling for word suggestions and emoji keyboard:

     osk
     osk-emoji

- Clock and weather indicators in panel dropdown menu: added styling introduced with gnome shell 3.32:

     clocks-weather

- System actions icons (e.g. reboot, lock) in overview: changed from default black to Arc blue:

     system-action

- App folders in overview: changed focused state to gray for consistency, fixed panel arrow in active state:

     app-folder-focus
     app-folder-active

### CODE REVIEW

**Comment by fossfreedom** [comment]
+1 from a quick code scan this is limited just to gnome-shell and the later versions of GS.  As such - excellent cleanup.  Merge now to allow much wider testing.

**Comment by drakkar1969** [comment]
Confirming that this is gnome shell only (and only for versions 3.30 and 3.32).
Awesome if you can merge so that people can test

**Comment by fossfreedom** [comment]
oh!

@NicoHood did you miss my ping request to make @drakkar1969 at contributor - please?

**Comment by NicoHood** [comment]
I want to get a clear statement from @jnsh first.

**Pull request merged**
